package uk.ac.aber.dcs.cs31620.focab.model

import android.os.Parcelable
import androidx.annotation.NonNull
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.parcelize.Parcelize

/**
 * Translation is a data class that represents a translation between two words. It
 * has three properties:
 * id: This is the primary key of the Translation object in the database and is
 * an integer type. It is set to be auto-generated by the database.
 * firstWord: This is a string that represents the first word in the translation.
 * secondWord: This is a string that represents the second word in the translation.
 */

@Entity(tableName = "translations")
@Parcelize
data class Translation (
    @PrimaryKey(autoGenerate = true)
    @NonNull
    var id: Int = 0,
    var firstWord : String,
    var secondWord : String
        ) : Parcelable